version: '3'
services:
  config-server:
    build: .
    container_name: config-server
    environment:
      JAVA_OPTS: >
        -Dserver.port=8888
        -Djava.security.egd=file:/dev/./urandom
    ports:
      - 8888:8888